### ISSUE TITLE
Introducing the Catalyst Community Partner Highlights series

### ISSUE THREAD

**Issue by katiepratt** [czi-catalystproject/czi-catalystproject.github.io#100]
This issue tracks the drafting, review and approval for adding a new blog post to the Catalyst Project blog.

This issue is complete when: the copy of this page is approved and published on the website.

This blog post describes the initial collection of  seven community partner highlights, and will be cross-posted to CSCCE, 2i2c, and OLS blogs as part of a coordinated comms plan (available here: https://docs.google.com/document/d/1NbWQ8Xf3aRXOyHPBxhMuw-2K5SPLB7xIkuoROD-9zec/edit )

**Please edit and insert information enclosed by the <angled brackets> below**

Create a Google Doc in *Catalyst Project Team Drive > External Documentation > Blog posts > your_filename* to draft the copy for your new page, with a title of the form "[VERSION #] <your_title>" and append this title with "(ES)" if the draft is in Spanish.

Please consult the [Style Guide](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit?usp=sharing) for more information, including which metadata tags to choose from for your blog post.

Google doc for drafting copy: https://docs.google.com/document/d/1S0nYUa_igMINAd54bmPBn49ZYU8ISg779SIws3bEhbw/edit

**Roles**

- [x] Drafting content: @katiepratt 
- [x] Sub-team review: @LouWoodley 
- [x] Sub-team review: @jnywong 
- [x] Sub-team review: @Tajuddeen1 
- [x] Hand off to @katiepratt for final review @katiepratt 
- [x] Hand off to MD for translation @SLLDeC / @4iro
- [x] Hand off to @jnywong  to draft website previews - 2 separate posts
- [x] Final approval of English post by Katie @katiepratt 
- [ ] Final approval of Spanish post by Sabrina @SLLDeC / @4iro

**Comment by SLLDeC** [comment]
I'm adding Laura to this issue so she can manage the translation step in case it happens while I'm out of the office.

**Comment by jnywong** [comment]
Hey @katiepratt ! I've left suggestions for the draft in the doc. I really like how concise this overview is in introducing the series!

One thing to bear in mind is that if we want to publish by the end of this month before the IOI community call, then we will need to get a move on with reviews and translation. @lauracion let us know if you need more notice for the translations.

**Comment by katiepratt** [comment]
Thanks, @jnywong !! I've accepted all of these changes. @LouWoodley we're just waiting on your feedback on this post before it can be translated, if you have time when you're back in the office tomorrow (Tuesday).

**Comment by lauracion** [comment]
@jnywong, Irene Vazano, [@4iro](https://github.com/4iro),  will answer your question. Can you please add her to this project so she can be added and tagged on these issues? Thank you!

**Comment by katiepratt** [comment]
The English version of this blog post is all signed off and ready for translation, thank you @4iro ! (cc @jnywong )

**Comment by 4iro** [comment]
Hello @jnywong and @katiepratt, we can deliver the translation on October 28th. Is that time convenient for publishing and reviewing?

**Comment by jnywong** [comment]
@4iro October 28th sounds great, thank you for coordinating 🙌

**Comment by 4iro** [comment]
Hi @jnywong, the translated document is available [here](https://docs.google.com/document/d/1ZDSAZdiovxvRhHZ8O3231WP7uhogkHCiq3ARQGLSReg/edit?usp=drive_link). 
Please let me know if there is something else that needs my attention. Thank you!

**Comment by jnywong** [comment]
Website previews are available to preview.

Spanish preview 👉 https://catalyst-website--106.org.readthedocs.build/en/106/blog/community-highlight-intro-es.html
English preview 👉 https://catalyst-website--106.org.readthedocs.build/en/106/blog/community-highlight-intro-en.html

You can add comments directly to the pull request here: https://github.com/czi-catalystproject/czi-catalystproject.github.io/pull/106/files (hover over the line you want to make a suggestion, press the small '+' button that pops up, and leave a comment)
![Screenshot 2024-10-28 at 11 43 37](https://github.com/user-attachments/assets/5fcb4244-3047-4fc5-bc7c-c8a864807c88)

**Comment by jnywong** [comment]
@4iro let me know if https://catalyst-website--106.org.readthedocs.build/en/106/blog/community-highlight-intro-es.html looks good to you

**Comment by SLLDeC** [comment]
> @4iro let me know if https://catalyst-website--106.org.readthedocs.build/en/106/blog/community-highlight-intro-es.html looks good to you

@jnywong done through #110
