### ISSUE TITLE
About page for website

### ISSUE THREAD

**Issue by Tajuddeen1** [czi-catalystproject/czi-catalystproject.github.io#11]
This issue tracks the drafting, review and approval of the About page for the Catalyst website.

This issue is complete when: the copy of this page is approved and can be moved to GitHub ready for publishing on the website (at that point we need to move the copy to the "code" section of this repo on GitHub).

Google doc for drafting copy: 
https://docs.google.com/document/d/1jenDiZV7VQyzG1fFkKX5K72DfJpPnSwzsuDw50lc4jA/edit?usp=sharing

Roles
Drafting content: @katiepratt and @Tajuddeen1
Initial review: @LouWoodley
Coordination / project management: @Tajuddeen1
Review: corresponding project sub-teams
Handoff - @katiepratt hands off to @jnywong to prep for website publishing

 
- [x] Draft initial page content (Katie)
- [x]  Add missing information (Taj)
- [x]  Initial review (Lou)
- [ ]  Taj to ping Nico about CCAD logo/description (Taj)
- [ ]  Address edits / suggestions (Katie)
- [ ]  Coordinate any additional input needed (Taj)
- [ ]  Final signoff (Katie)
- [ ]  Handoff to Jenny (Katie)

**Comment by Tajuddeen1** [comment]
@katiepratt I have added the missing information

**Comment by katiepratt** [comment]
Re-worked this page, too.

**Comment by katiepratt** [comment]
Hmmm it could be, but we have a bit of a naming challenge, since we also have the "team" page for individuals. I like how you've made the boxes around the organizations. 

Maybe one option would be to include those organization boxes on the Team page, at the top of each section? Ie, start with the 2i2c org info, then the individuals, etc. That would also make for a long page, but at least it would make sense in terms of what information is there.

**Comment by jnywong** [comment]
> Maybe one option would be to include those organization boxes on the Team page, at the top of each section? Ie, start with the 2i2c org info, then the individuals, etc. That would also make for a long page, but at least it would make sense in terms of what information is there.

This suggestion is good – I also think that the individual team member informatoin might take some time to finalise, so I think putting the organization boxes on the team page for now works.

**Comment by katiepratt** [comment]
Cool. Also there's still a full stop in the button at the top of the about page. In general, let's not have full stops in the buttons. Thanks!
