### ISSUE TITLE
Community partnership page for website

### ISSUE THREAD

**Issue by Tajuddeen1** [czi-catalystproject/czi-catalystproject.github.io#13]
This issue tracks the drafting, review and approval of the Community partnership page for the Catalyst website.

This issue is complete when: the copy of this page is approved and can be moved to GitHub ready for publishing on the website (at that point we need to move the copy to the "code" section of this repo on GitHub).

Google doc for drafting copy: 
https://docs.google.com/document/d/1Sb02bGP4p_rbQk1SnbXHfAgjd1YmRgBDNuiQtafZa5M/edit?usp=sharing

Roles
Drafting content: @katiepratt and @Tajuddeen1
Initial review: @LouWoodley
Coordination / project management: @Tajuddeen1
Review: corresponding project sub-teams
Handoff - @katiepratt hands off to @jnywong to prep for website publishing

 

- [x] Draft initial page content (Katie)
- [x]  Add missing information (Taj)
- [x]  Initial review (Lou)
- [x]  Send to sub-teams for review (Taj) - N/A
- [ ]  Address edits / suggestions - rework the section on governance (Katie and Lou)
- [ ]  Taj to email communities about logos (Taj)
- [ ] Taj to update list of current community partners. (Taj)
- [ ]  Final signoff (Katie)
- [ ]  Handoff to Jenny (Katie)

**Comment by Tajuddeen1** [comment]
@katiepratt I have added the missing information

**Comment by katiepratt** [comment]
Re-worked this page - tried to simplify significantly

**Comment by jnywong** [comment]
I've generated a website preview at https://github.com/czi-catalystproject/website/pull/23.

For now, I have avoided the use of current community partner logos due to potential copyright violations. I think the section for Current Community Partners could be split into its own page entirely?

Please let me know your comments and suggestions 🙂

**Comment by katiepratt** [comment]
My understanding re copyright and using logos is that so long as you are using the logo for editorial or informational purposes (ie, not using it to imply an endorsement) then it's fine to use. Is that the concern here?

**Comment by katiepratt** [comment]
- Can you change button text to “Apply to become a Community Partner” please
- Splitting current Community Partners to a child page makes sense to me - perhaps create a button for the bottom of the page that links over there that says “View current Community Partners”

**Comment by jnywong** [comment]
> - [x] Can you change button text to “Apply to become a Community Partner” please
> - [x] Splitting current Community Partners to a child page makes sense to me - perhaps create a button for the bottom of the page that links over there that says “View current Community Partners”

I've also added the logos where available and created placeholders for partners without logos.
