### ISSUE TITLE
Contacts page for website

### ISSUE THREAD

**Issue by Tajuddeen1** [czi-catalystproject/czi-catalystproject.github.io#14]
This issue tracks the drafting, review and approval of the Contacts page for the Catalyst website.

This issue is complete when: the copy of this page is approved and can be moved to GitHub ready for publishing on the website (at that point we need to move the copy to the "code" section of this repo on GitHub).

Google doc for drafting copy: 
https://docs.google.com/document/d/1Q0w-Sff2i_kC_Q6d0C238oUKHmbGc26Xq9Jy8Gp9lgE/edit?usp=sharing

Roles
Drafting content: @katiepratt and @Tajuddeen1
Initial review: @LouWoodley
Coordination / project management: @Tajuddeen1
Review: corresponding project sub-teams
Handoff - @katiepratt hands off to @jnywong to prep for website publishing

 

- [x] Draft initial page content (Katie)
- [x]  Add missing information (Taj)
- [x]  Initial review (Lou)
- [x]  Send to sub-teams for review (Taj) - N/A
- [x]  Address edits / suggestions (Katie)
- [x]  Jenny to check re 2i2c approval (Jenny)
- [x]  Final signoff (Katie)
- [x]  Handoff to Jenny (Katie)

**Comment by Tajuddeen1** [comment]
@katiepratt I don't have anything to add to the contacts page. However, I would like us to agree on the contact channel. Through the documents I have seen at least 2 contact options
tajuddeen@we-are-ols.org
catalyst-project-core-team@googlegroups.com

**Comment by jnywong** [comment]
I've generated a website preview at #22.

Please let me know your comments and suggestions 🙂

**Comment by katiepratt** [comment]
This one looks good to me!

**Comment by jnywong** [comment]
This issue depends on #12 and #13.
