### ISSUE TITLE
Home page for website

### ISSUE THREAD

**Issue by Tajuddeen1** [czi-catalystproject/czi-catalystproject.github.io#15]
This issue tracks the drafting, review and approval of the Home page for the Catalyst website.

This issue is complete when: the copy of this page is approved and can be moved to GitHub ready for publishing on the website (at that point we need to move the copy to the "code" section of this repo on GitHub).

Google doc for drafting copy: 
https://docs.google.com/document/d/1egDnaD5wkjqJ57sQiiNjp2JqYcNjUjgL-X5kIuqjh20/edit?usp=sharing

Roles
Drafting content: @katiepratt and @Tajuddeen1
Initial review: @LouWoodley
Coordination / project management: @Tajuddeen1
Review: corresponding project sub-teams
Handoff - @katiepratt hands off to @jnywong to prep for website publishing

 

- [x] Draft initial page content (Katie)
- [x]  Add missing information (Taj)
- [x]  Initial review (Lou)
- [x]  Send to sub-teams for review (Taj) - N/A here
- [x]  Address edits / suggestions (Katie)
- [x]  Jenny to check with James re final approval from 2i2c
- [x]  Final signoff (Katie)
- [x]  Handoff to Jenny (Katie)
- [x] Build preview (Jenny)
- [ ] Iterate changes (Katie & Jenny)
- [ ] Publish to main website (Jenny)

**Comment by Tajuddeen1** [comment]
@katiepratt I have added missing information

**Comment by katiepratt** [comment]
@LouWoodley I've taken another pass at this - but it might make more sense to review all of the content at the same time (I'm almost through "About" and "Community Partnership" also)

**Comment by katiepratt** [comment]
Looking good! A couple of things: 
- "The Catalyst Project is staffed by members of the following organisations" needs a colon at the end
- The org logos don't link out (yet....maybe you're still working on this!). I noticed the 2i2c and OLS ones let you click on them, but they just open the image
- Also re the org logos - we probably need to decide on an order that makes sense visually and for the project - @Tajuddeen1 do you have any thoughts here? I think 2i2c should be first, after that I am less certain. 
- Can you also make the CZI image in the footer link out to their website? 
- Also, can you link to CZI in the intro text?
- Again this is perhaps in progress, but on the left rail there's a "register" menu item right at the top. I think this is supposed to be for the community partnership reg form - if so, I think it probably makes more sense as a child of the community partnership page. What do you think? I definitely think it should be above "About"

That's all for now, if I think of anything else I'll be back :)

**Comment by jnywong** [comment]
- [x]     "The Catalyst Project is staffed by members of the following organisations" needs a colon at the end
- [x]     The org logos don't link out (yet....maybe you're still working on this!). I noticed the 2i2c and OLS ones let you click on them, but they just open the image **Jenny: All done – just waiting on the CCAD logo now :)**
- [ ]     Also re the org logos - we probably need to decide on an order that makes sense visually and for the project - @Tajuddeen1 do you have any thoughts here? I think 2i2c should be first, after that I am less certain.
- [x]     Can you also make the CZI image in the footer link out to their website?
- [x]     Also, can you link to CZI in the intro text?
- [x]     Again this is perhaps in progress, but on the left rail there's a "register" menu item right at the top. I think this is supposed to be for the community partnership reg form - if so, I think it probably makes more sense as a child of the community partnership page. What do you think? I definitely think it should be above "About" **Jenny: I've hidden this for now, I am not sure we will need this for much longer seeing as we will only be onboarding communities up until the end of April**

**Comment by katiepratt** [comment]
Awesome! Looking good.

**Comment by katiepratt** [comment]
Yeah - let's talk about the logo order on Wednesday :)
