### ISSUE TITLE
Training page for website

### ISSUE THREAD

**Issue by Tajuddeen1** [czi-catalystproject/czi-catalystproject.github.io#16]
This issue tracks the drafting, review and approval of the Training page for the Catalyst website.

This issue is complete when: the copy of this page is approved and can be moved to GitHub ready for publishing on the website (at that point we need to move the copy to the "code" section of this repo on GitHub).

Google doc for drafting copy: 
https://docs.google.com/document/d/16bfp5qIDdqrlOAo_sxu_NOy6_4VaIXm6fmGq17V1l7M/edit?usp=sharing

Roles
Drafting content: @katiepratt and @Tajuddeen1
Initial review: @LouWoodley
Coordination / project management: @Tajuddeen1
Review: corresponding project sub-teams
Handoff - @katiepratt hands off to @jnywong to prep for website publishing

- [x] Draft initial page content (Katie)
- [x]  Add missing information (Taj)
- [x]  Initial review (Lou)
- [ ]  ~~Send to sub-teams for review (Taj) N/A~~
- [ ]  Address edits / suggestions (Katie)
- [x] Jenny to check with James re approval (Jenny)
- [ ]  Final signoff (Katie)
- [ ]  Handoff to Jenny (Katie)

Depends on resolving #13 and #14

**Comment by Tajuddeen1** [comment]
@katiepratt I have added the missing information

**Comment by LouWoodley** [comment]
I've reviewed. this one now too! I think we're in good shape to update these pages tomorrow.

**Comment by jnywong** [comment]
I've generated a preview for this one. Will need to discuss how trainees can register to close this one out.
