### ISSUE TITLE
Add a list of running Catalyst Project hubs

### ISSUE THREAD

**Issue by jmunroe** [czi-catalystproject/czi-catalystproject.github.io#36]
2i2c maintains a [list of running hubs](https://infrastructure.2i2c.org/reference/hubs/) across all of its infrastructure.

"It would cool to have a localized version for the Catalyst hubs on the new web site. "

This issue is complete when: the copy of this page is approved and published on the website.

Create a Google Doc in *Catalyst Project Team Drive > External Documentation > Blog Post > your_filename* to draft the copy for your new page.

Google doc for drafting copy: <paste a link to the Google Doc here>

**Roles**

- [ ] Drafting content: @jmunroe
- [ ] Sub-team review: @jnywong
- [ ] Handoff: @katiepratt to provide editorial review
- [ ] Draft website preview: @jnywong to prepare a preview for website publishing
- [ ] Final sign-off: @katiepratt
- [ ] New page is published: @jnywong

**Comment by LouWoodley** [comment]
Hi @jmunroe  - do you have specific ideas in mind for how you would like this to work e.g., if we added URLs linking to each live hub under each community partner listing on the [community partners page](https://catalystproject.cloud/current-community-partners.html#), would that be sufficient? Or do you need the info to be in a similarly formatted table to the one on the 2i2c website?

**Comment by jmunroe** [comment]
This was primarily capturing the request made in the monthly team meeting. 

No, I don't think the full table that 2i2c uses is needed to. I agree that adding the URL for each community hub is good.

But having this information as table (columns: hub url, community name, AWS or GCP) is also useful page to have. It is a table like that I was planning on proposing.
