### ISSUE TITLE
Create a catalyst usage policy

### ISSUE THREAD

**Issue by haroldcampbell** [czi-catalystproject/czi-catalystproject.github.io#38]
Draft a Catalyst Project shared responsibility document on data privacy. 

This needs to clarify that users are responsible for following the local data privacy rules/legislation. This document should be written in a plain language description supplemented by references and links to more formal documentation.

### Definition of Done/Measure of Success
- [ ] @jnywong to create first draft
- [ ] Community partnership sub-team to review
- [ ] Hand off to MD for translation @SLLDeC
- [ ] Hand off to Jenny to draft website previews - 2 separate posts @jnywong
- [ ] Final approval of English post by Katie @katiepratt
- [ ] Final approval of Spanish post by Sabrina @SLLDeC 
- [ ] Publish 🚀

**Comment by LouWoodley** [comment]
Noting the website team discussed this on April 10th at our weekly meeting. One option for this (in addition to any privacy policy updates) is to create an FAQs page where e.g., one question might be "what data is appropriate to share on our  hub?" We could answer the question in 1 -2 sentences and then link to a blog post with more information and an example case study.

**Comment by jnywong** [comment]
Worth noting that partner communities should understand their responsibility towards protecting sensitive data used for bioinformatics/medical health research purposes. 

Related to https://github.com/czi-catalystproject/Project-Board/issues/166

**Comment by jnywong** [comment]
Answered in the FAQs section as suggested by Lou: https://catalystproject.cloud/faqs.html#can-i-store-sensitive-data-such-as-health-records-and-patient-information-on-the-hub
