### ISSUE TITLE
FAQs page

### ISSUE THREAD

**Issue by LouWoodley** [czi-catalystproject/czi-catalystproject.github.io#41]
This issue tracks the drafting, review and approval for adding a new page to the Catalyst website (a separate template issue for blog posts is coming soon).

This issue is complete when: the copy of this FAQs page is approved and published on the website.

### Google doc for drafting copy

https://docs.google.com/document/d/1wynnvQQ1_CAUxmmVuDZFHXWi0RLkVeaDKoerXKdjCOc/edit#heading=h.d5tnu211dtng

### Current FAQs page

https://catalystproject.cloud/faqs.html

### Roles

- [ ] Drafting content: @jnywong, @katiepratt, @SLLDeC, @elletjies, @KatherineSkinner 
- [ ] Sub-team review: @jnywong 
- [ ] Handoff: @katiepratt to provide editorial review
- [ ] Draft website preview: @jnywong to prepare a preview for website publishing
- [ ] Final sign-off: @katiepratt
- [ ] New page is published: @jnywong

**Comment by SLLDeC** [comment]
Hi, I added some questions the communities asked during the onboarding process to the document.

**Comment by elletjies** [comment]
@jnywong and @LouWoodley what timeline are we looking at? I am going to be away from my desk from 2-18 August

**Comment by jnywong** [comment]
Hey @elletjies ! If you could aggregate the common FAQs you have encountered from onboarding Catalyst community partners into the doc by July 31 that would be fantastic.

If you already have a collection a bank of questions from elsewhere, please share and signpost so that I can extract them :)

**Comment by elletjies** [comment]
@jnywong I have added a couple of questions I have been asked :)
