### ISSUE TITLE
New blog post: Welcome to the blog -  what it's going to be for

### ISSUE THREAD

**Issue by LouWoodley** [czi-catalystproject/czi-catalystproject.github.io#42]
This issue tracks the creation of a blog post describing the purpose of the CP blog

It is done when the blog post is published in English and Spanish

Link to Google doc for drafting: https://docs.google.com/document/d/1sfr5pjcNoNFKS0QhEYTYVfP65Xh-D3GhQrSmoK9vN0Y/edit

**Checklist**

- [x] Draft post @katiepratt 
- [x] Review post @LouWoodley  
- [x] Hand off to Katie for final review @katiepratt 
- [x] Hand off to MD for translation @SLLDeC – paused for now due to limited capacity from MD until the end of April
- [x] Hand off to Jenny to draft website previews - 2 separate posts @jnywong 
- [x] Final approval of English post by Katie @katiepratt 
- [ ] Final approval of Spanish post by Sabrina @SLLDeC

**Comment by katiepratt** [comment]
Hi @LouWoodley - I've created a first draft of this blog post in the linked GDoc. Feel free to edit/make suggestions. 

I also started a "Tag Taxonomy" in the style guide doc (https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit#heading=h.kf17shhev5kr). 

Please do add additional tags. I need to connect with Jenny about how these work, though (as noted in the draft blog post).

**Comment by LouWoodley** [comment]
Thanks, Katie! I made a few small edits to the  post - I think it's looking good. I suggested a few potential additional tags in the style guide. Once we understand from Jenny how these works we'll know better how rigid we need to be about these upfront versus evolving as we go.

**Comment by katiepratt** [comment]
Thanks, @jnywong! A couple of quick changes: 

"All reflection posts will also be tagged, and you will be able to find them all by filtering on the Team reflections tag." <should probably remove this until we actually have tags

"We are also working on creating a Spanish version of this website, and all blog posts will be available in both English and Spanish." Perhaps we should change this to "We are also working on creating a Spanish version of this website, and ultimately all blog posts will be available in both English and Spanish."

Otherwise, looks great!

**Comment by jnywong** [comment]
Blog functionality is enabled! 🚀

**Comment by jnywong** [comment]
I will update the blog post template with the following information:

### Metadata

Each blog post is associated with metadata such as

* Date
* Author
* Tags
* Language

Posts can have multiple authors and tags. See [0. Catalyst Project Style Guide – Tag Taxonomy](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit#heading=h.kf17shhev5kr) for a list of tags.

### Bylines

The first paragraph of your post will be treated as the byline to introduce your post. This will be formatted in _italics _ and inserted below the title of the blog post and will show up in the as an excerpt in the blog index.

**Comment by SLLDeC** [comment]
I checked the document in the [above link](https://docs.google.com/document/d/1sfr5pjcNoNFKS0QhEYTYVfP65Xh-D3GhQrSmoK9vN0Y/edit), and it has a comment that I assume that should be marked as solved. 
Besides that, could I consider the document ready to be translated and pass it over to the translator?

**Comment by jnywong** [comment]
Hi @SLLDeC ! Sorry for the slow response, I am at a conference currently. Yes, I think we can mark the above document as the final draft ready for translation! Let me know how this progresses 👍

**Comment by SLLDeC** [comment]
The translated blog post is available in this [link](https://docs.google.com/document/d/1hDxEggpNwXLcnNiw-X7UwQKxSK1p9isXenjmSOhDQ14/edit).

I left a comment regarding the translation of the tag name. Also. keep in mind that the links are the same as in the English version. This will need to be updated once the website has the Spanish version of the content.

**Comment by jnywong** [comment]
Hey @SLLDeC I have requested a review on PR #58, which includes the Spanish version of the blog post in the preview (scroll down to the bottom > show all checks to see the preview).

A few points (for @katiepratt too)

- Is there a way we can credit the translator in the author list? Or shall we just include MetaDocencia as a co-author for all translated posts?
- The current blog setup allows "language" as a piece of metadata associated with all blog posts, which allows you to click on the language in the left sidebar in the Blog section to view all posts in that language.
- I have included Spanish translations of blog tags as separate tags.

I think the structure of the blog could change to separate the Spanish and English content entirely if we restructure the website to localise for Spanish throughout. However, this work to is not in the pipeline quite yet, so I think the current method is safe to try for now.

**Comment by SLLDeC** [comment]
Hi! I reviewed, suggested, and left comments on the Spanish translations of blog tags. 

Regarding the review of the PR, the tags used for the post are some of the ones I suggest to change in the [Catalyst Project Style Guide](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit). Should I wait for this to be reviewed by you or do you prefer to publish the post with the tags as they are and change it later?

**Comment by jnywong** [comment]
Thank you for the tag suggestions in the Style Guide, that's *really* helpful! I'll get the draft updated now.
