### ISSUE TITLE
Add Community Onboarding documents in Spanish and English

### ISSUE THREAD

**Issue by jnywong** [czi-catalystproject/czi-catalystproject.github.io#46]
This issue tracks the creation of a blog post to publicize the Community Onboarding Documents

It is done when the blog post is published in English and Spanish

Link to Google doc for drafting: XX

**Checklist**

- [ ] Draft post @jnywong 
- [ ] Review post @elletjies 
- [ ] Hand off to Katie for final review @katiepratt
- [ ] Hand off to MD for translation @SLLDeC
- [ ] Hand off to Jenny to draft website previews - 2 separate posts @jnywong
- [ ] Final approval of English post by Katie @katiepratt
- [ ] Final approval of Spanish post by Sabrina @SLLDeC

**Comment by jnywong** [comment]
I've added links to the documents on the website: https://catalystproject.cloud/faqs.html#where-can-i-find-the-onboarding-document

**Comment by elletjies** [comment]
This looks great @jnywong!
