### ISSUE TITLE
Publicise Catalyst Project website to Community Partners

### ISSUE THREAD

**Issue by jnywong** [czi-catalystproject/czi-catalystproject.github.io#49]
Hi @SLLDeC and @elletjies ,

@katiepratt from CSCCE has drafted an email to publicise our recently released website to our community partners. 

Would you be able to send this out on our behalf please (draft below)?

> Dear _name_, 
> 
> I’m writing to let you know that the English version of the website for the Catalyst Project is now live:  [https://catalystproject.cloud/](https://catalystproject.cloud/). A Spanish version of the site will be available soon. 
> 
> As a Community Partner in this project, [you are listed on the website](https://catalystproject.cloud/current-community-partners.html). You can also find information about available [training through the Catalyst Project](https://catalystproject.cloud/training.html), as well as stay up-to-date on news and activities on the blog. 
> 
> We would appreciate any feedback you have about the website - you can either reply to this email, or submit your feedback via the Catalyst Project GitHub repo (I’ve included detailed instructions for how to do this below). 
> 
> We are also in the process of creating an “FAQ” page, so if you have suggestions for things to include there (e.g., questions you had while getting set up as a community partner), please let me know. 
> 
> All the best, 
> 
> -Angelique/Sabrina
> 
> **Instructions for submitting updates to the Catalyst Project website**
> 
> To suggest an update or correction on existing content, e.g., you spotted a typo or need to update a team members’ information:
> 
> 1. **Go to the [Catalyst website GitHub repository](https://github.com/czi-catalystproject/czi-catalystproject.github.io)**
> 2. From the top menu, **click on Issues**. You will see a list of [ongoing issues](https://github.com/czi-catalystproject/czi-catalystproject.github.io/issues)
> 3. **Click on the green “New Issue” button** and then **select the template called “Suggest minor edits”.**
> 4. This will display a template issue where you can **add your request details**
> 5. Tips:
>     - Please add a direct link to the place on the website that you would like to be updated. If you hover over headings on the website this will reveal an anchored URL. This will help the website team to find the correct place.
> 6. When you have added all the required info, **click the “submit new issue” button**
> 7. You can expect Jenny to respond to your issue within a week. She may ask clarifying questions in the issue comment so please make sure you have notifications enabled. Jenny will likely package multiple issues into a next release so you may not see a resolution to your issue immediately.

**Comment by elletjies** [comment]
@jnywong this is great! I will send out the emails today.

**Comment by lauracion** [comment]
@jnywong thank you! 

If this email comes from the MD team will must translate it to Spanish because we always communicate in Spanish with Latin American communities. All our time for Catalyst is currently being used to address the bottleneck of new community onboarding. 

Thus, to have this email out timely two possibilities come to mind:

1) Someone else at Catalyst sends this email to Latin American communities in English at their earliest convenience or
2) MetaDocencia's team sends it in Spanish once we are on the other end of the current onboarding crunch, date tbd 😃 

Please let us know what works best. Thank you so much for your help and understanding with this! 💮

**Comment by jnywong** [comment]
Hi @lauracion!

You're welcome. I understand that the onboarding crunch is the main focus for MetaDocencia at this time, so I am happy with option 2.

I'll pick this up again with @SLLDeC after April has passed :)

**Comment by SLLDeC** [comment]
I sent out the emails. Thank you for your understanding!
