### ISSUE TITLE
Mission and vision page for website

### ISSUE THREAD

**Issue by LouWoodley** [czi-catalystproject/czi-catalystproject.github.io#8]
This issue tracks the drafting, review and approval of the Mission page for the Catalyst website.

This issue is complete when: the copy of this page is approved and can be moved to GitHub ready for publishing on the website (at that point we need to move the copy to the "code" section of this repo on GitHub).

Google doc for drafting copy: https://docs.google.com/document/d/1Sh2um4hxLErbVdc96_Zw2LaotcYuT3vssCdYrW_aUd8/edit#heading=h.rr8fm2gz946v 

**Roles**
Drafting content: @katiepratt and @Tajuddeen1 
Initial review: @LouWoodley 
Coordination / project management: @Tajuddeen1 
Review: corresponding project sub-teams
Handoff - @katiepratt hands off to @jnywong to prep for website publishing

- [x] Draft initial page content (Katie)
- [x] Add missing information (Taj)
- [ ] Initial review (Lou)
- [ ] Send to sub-teams for review (Taj)
- [ ] Address edits / suggestions (Katie)
- [ ] Coordinate any additional input needed (Taj)
- [ ] Final signoff (Katie)
- [ ] Handoff to Jenny (Katie)

**Comment by Tajuddeen1** [comment]
@katiepratt I have nothing to add

**Comment by katiepratt** [comment]
After re-writing the "About" page, and then re-visiting this page, I'm not sure this page adds much to the overall communication of what Catalyst is doing. Perhaps we can discuss the purpose of this page at our next meeting and that might help us understand what needs to be there?
