### ISSUE TITLE
Write reflections on Hub Champion Training in a blog post

### ISSUE THREAD

**Issue by jnywong** [czi-catalystproject/czi-catalystproject.github.io#87]
This issue tracks the drafting, review and approval for adding a new blog post to the Catalyst Project blog.

This issue is complete when: the copy of this page is approved and published on the website.

**Please edit and insert information enclosed by the <angled brackets> below**

Google Doc draft 👉 https://docs.google.com/document/d/1xDE3s4a7nU5pE5M2xx_vBaHHxWl5tQr9-H4MhRW0wbQ/edit?usp=sharing

Please consult the [Style Guide](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit?usp=sharing) for more information, including which metadata tags to choose from for your blog post.

**Roles**

- [x] Drafting content: @jnywong 
- [x] Final approval of English post by Katie @katiepratt 
- [x] Hand off to Crowdin for translation
- [x] Final approval of Spanish post by Sabrina @SLLDeC
- [x] Hand off to Jenny to draft website previews - 2 separate posts @jnywong

**Comment by jnywong** [comment]
Hey @katiepratt !

This one is ready for you to review. 

Once that's approved, I'll work on getting this translated into Spanish with Crowdin 👍

**Comment by katiepratt** [comment]
Looks good, Jenny! I've added some edits and comments. Let me know if you'd like me to take another look, or if everything makes sense to you no worries. Have a good weekend.

**Comment by jnywong** [comment]
Thanks for the suggestions @katiepratt ! I've added them in and passed the copy to Crowdin for translation into Spanish (Latin America).

@Tajuddeen1 FYI I am keeping track of costs in this spreadsheet: https://docs.google.com/spreadsheets/d/1VjE9L6Q9SNc3atbGxJGqHV_lE4IODW2sif3BTAto5ew/edit?usp=sharing.

**Comment by jnywong** [comment]
@SLLDeC the proofreading task is ready for you on Crowdin 😄 

https://crowdin.com/project/catalyst-project/tasks/48
