### ISSUE TITLE
Community Partner Highlight - AiBST

### ISSUE THREAD

**Issue by katiepratt** [czi-catalystproject/czi-catalystproject.github.io#91]
This issue tracks the drafting, review and approval for adding a new blog post to the Catalyst Project blog.

This issue is complete when: the copy of this page is approved and published on the website.

**Please edit and insert information enclosed by the <angled brackets> below**

Create a Google Doc in *Catalyst Project Team Drive > External Documentation > Blog posts > your_filename* to draft the copy for your new page, with a title of the form "[VERSION #] <your_title>" and append this title with "(ES)" if the draft is in Spanish.

Please consult the [Style Guide](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit?usp=sharing) for more information, including which metadata tags to choose from for your blog post.

Google doc for drafting copy:(https://docs.google.com/document/d/1BgAY9Hg1TruMsS3ysKX2_2iq33eIDf_jramZdBRAurc/edit)

**Roles**

- [x] Drafting content: @katiepratt
- [x] Sub-team review: @jnywong @Tajuddeen1 @LouWoodley 
- [x] Send to Author for sign off @katiepratt 
- [x] Any corrections made / final sign off @katiepratt 
- [x] Hand off to MD for translation @SLLDeC
- [x] Hand off to Jenny to draft website previews - 2 separate posts @jnywong 
- [x] Final approval of English post by Katie @katiepratt 
- [x] Final approval of Spanish post by Sabrina @SLLDeC

**Comment by jnywong** [comment]
Hey @katiepratt! I've read through and reviewed the draft and it looks brilliant 👍No changes are required from me.

I think we can improve a couple of steps in the **Roles** task list so that you don't need to provide both an editorial _and_ final review.

@SLLDeC shall I update handling blog post translations via Crowdin or shall we hand this off to MetaDocencia as originally proposed?

**Comment by Tajuddeen1** [comment]
Looks good

**Comment by LouWoodley** [comment]
Looks good to me too - thanks @katiepratt!

**Comment by SLLDeC** [comment]
Hi @katiepratt, I will proceed with the translation to have it ready by Jenny's return so she can draft the website previews.

**Comment by SLLDeC** [comment]
Hi @jnywong, the translated document is available [here](https://docs.google.com/document/d/1r1SfE5EMYMtanXOW95ZFiohltcaG9nEv4JlgsJjhqqs/edit?usp=drive_link).

**Comment by jnywong** [comment]
Website previews can be found here: https://github.com/czi-catalystproject/czi-catalystproject.github.io/pull/98
