### ISSUE TITLE
Community Partner Highlight - MUST

### ISSUE THREAD

**Issue by katiepratt** [czi-catalystproject/czi-catalystproject.github.io#92]
This issue tracks the drafting, review and approval for adding a new blog post to the Catalyst Project blog.

This issue is complete when: the copy of this page is approved and published on the website.

**Please edit and insert information enclosed by the <angled brackets> below**

Create a Google Doc in *Catalyst Project Team Drive > External Documentation > Blog posts > your_filename* to draft the copy for your new page, with a title of the form "[VERSION #] <your_title>" and append this title with "(ES)" if the draft is in Spanish.

Please consult the [Style Guide](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit?usp=sharing) for more information, including which metadata tags to choose from for your blog post.

Google doc for drafting copy: https://docs.google.com/document/d/1heIpLtHr4VZMj22jiF4HS0lFCYFHcUZ6F31yYHNJEiE/edit

**Roles**

- [x] Drafting content: @katiepratt 
- [x] Sub-team review: @jnywong @Tajuddeen1 @LouWoodley 
- [x] Send to Author for sign off @katiepratt 
- [x] Any corrections made / final sign off @katiepratt 
- [x] Hand off to MD for translation @SLLDeC
- [x] Hand off to @jnywong to draft website previews - 2 separate posts
- [x] Final approval of English post by Katie @katiepratt 
- [x] Final approval of Spanish post by Sabrina @SLLDeC

**Comment by Tajuddeen1** [comment]
Reviewed. Looks good

**Comment by LouWoodley** [comment]
The post looks good - and noting that there are a couple of follow up items too - perhaps we can discuss these at our next check in.

**Comment by katiepratt** [comment]
Noting that I've asked the authors about their publications, and updated [our shared notes doc](https://docs.google.com/document/d/14nJqZZA-v1ddLTbCOMY2dV8fp3ZPczaYIYmEC93hwEU/edit) so that we are ready to discuss at our next meeting.

**Comment by katiepratt** [comment]
Today (Monday, 23 September) was the deadline for any corrections/edits. None received, so this can be translated / prepped for publication. 

Note: @jnywong we may need to reach out again re publications, since I got no answer.

**Comment by SLLDeC** [comment]
Hi @jnywong, the translated document is available [here](https://docs.google.com/document/d/1C102Vdzulj8zvL3Y2B27QE7Yv24OHL8O8jlN7wQs-eI/edit#heading=h.9tqe084ssxg2).

**Comment by jnywong** [comment]
Heya! The website previews can be found here: https://github.com/czi-catalystproject/czi-catalystproject.github.io/pull/99

**Comment by katiepratt** [comment]
Love how the photos look in this one :)

**Comment by jnywong** [comment]
Thanks @SLLDeC ! I have applied your suggestions.

**Comment by jnywong** [comment]
In terms of publication dates, @katiepratt is working on a plan
