### ISSUE TITLE
Community Partner Highlight - MolerHealth

### ISSUE THREAD

**Issue by katiepratt** [czi-catalystproject/czi-catalystproject.github.io#93]
This issue tracks the drafting, review and approval for adding a new blog post to the Catalyst Project blog.

This issue is complete when: the copy of this page is approved and published on the website.

**Please edit and insert information enclosed by the <angled brackets> below**

Create a Google Doc in *Catalyst Project Team Drive > External Documentation > Blog posts > your_filename* to draft the copy for your new page, with a title of the form "[VERSION #] <your_title>" and append this title with "(ES)" if the draft is in Spanish.

Please consult the [Style Guide](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit?usp=sharing) for more information, including which metadata tags to choose from for your blog post.

Google doc for drafting copy: https://docs.google.com/document/d/1R4q2AcPvpkrHM5rHoP-rWbAHdz-C04C8pkXnpjubiP0/edit

**Roles**

- [x] Drafting content: @katiepratt 
- [x] Sub-team review: @jnywong @Tajuddeen1 @LouWoodley 
- [x] Send to Author for sign off @katiepratt 
- [x] Any corrections made / final sign off @katiepratt 
- [x] Hand off to MD for translation @SLLDeC
- [x] Hand off to @jnywong to draft website previews - 2 separate posts 
- [x] Final approval of English post by Katie @katiepratt 
- [x] Final approval of Spanish post by Sabrina @SLLDeC

**Comment by Tajuddeen1** [comment]
Looks good

**Comment by LouWoodley** [comment]
Thanks @katiepratt - the post copy looks fine and I think we should address Jenny's comments in the doc before publishing it.

**Comment by katiepratt** [comment]
Noting that I have sent this to the author for sign off, but as per Lou's comment I've added the comments about this post to our [shared notes doc](https://docs.google.com/document/d/14nJqZZA-v1ddLTbCOMY2dV8fp3ZPczaYIYmEC93hwEU/edit) for discussion at our next meeting.

**Comment by katiepratt** [comment]
Today (Monday, 23 September) was the deadline for any corrections/edits. None received, so this can be translated / prepped for publication (hold on publication, see previous comment).

**Comment by jnywong** [comment]
Hey just catching up on this! Good to see that my comments on the draft shouldn't block the translation/publication and that we are preparing to find ways to support this community in a more targeted way 👍

**Comment by SLLDeC** [comment]
Hi @jnywong, the translated document is available [here](https://docs.google.com/document/d/1x8mKsBxQa11ysoXzTtpOssC4kvq6LCpY5IwbV7zwYAc/edit#heading=h.9tqe084ssxg2).

**Comment by jnywong** [comment]
@katiepratt @SLLDeC ready for final approval #101
