### ISSUE TITLE
Community Partner Highlight - NM-AIST

### ISSUE THREAD

**Issue by katiepratt** [czi-catalystproject/czi-catalystproject.github.io#94]
This issue tracks the drafting, review and approval for adding a new blog post to the Catalyst Project blog.

This issue is complete when: the copy of this page is approved and published on the website.

**Please edit and insert information enclosed by the <angled brackets> below**

Create a Google Doc in *Catalyst Project Team Drive > External Documentation > Blog posts > your_filename* to draft the copy for your new page, with a title of the form "[VERSION #] <your_title>" and append this title with "(ES)" if the draft is in Spanish.

Please consult the [Style Guide](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit?usp=sharing) for more information, including which metadata tags to choose from for your blog post.

Google doc for drafting copy: (https://docs.google.com/document/d/1jRquAS7AJjlbufH5cKck0Z8ah3WEdL45tlxNP45YY60/edit)

**Roles**

- [x] Drafting content: @katiepratt 
- [x] Sub-team review: @jnywong @Tajuddeen1 @LouWoodley 
- [x] Send to Author for sign off @katiepratt 
- [x] Any corrections made / final sign off @katiepratt 
- [x] Hand off to MD for translation @SLLDeC
- [x] Hand off to Jenny to draft website previews - 2 separate posts @jnywong 
- [x] Final approval of English post by Katie @katiepratt 
- [x] Final approval of Spanish post by Sabrina @SLLDeC

**Comment by Tajuddeen1** [comment]
Looks good to me

**Comment by LouWoodley** [comment]
Looks good to me too - and great to read more positive feedback about the hub champions training! @katiepratt

**Comment by katiepratt** [comment]
Today (Monday, 23 September) was the deadline for any corrections/edits. None received, so this can be translated / prepped for publication.

**Comment by SLLDeC** [comment]
Hi @jnywong, the translated document is available [here](https://docs.google.com/document/d/1-zqGuotMW1u5CZZXgm0zGvMZ7Ovxa-PawfyW8tgbe8Q/edit#heading=h.9tqe084ssxg2).

**Comment by jnywong** [comment]
@SLLDeC @katiepratt ready for final approval #102
