### ISSUE TITLE
Community Partner Highlight - CICADA

### ISSUE THREAD

**Issue by katiepratt** [czi-catalystproject/czi-catalystproject.github.io#97]
This issue tracks the drafting, review and approval for adding a new blog post to the Catalyst Project blog.

This issue is complete when: the copy of this page is approved and published on the website.

**Please edit and insert information enclosed by the <angled brackets> below**

Create a Google Doc in *Catalyst Project Team Drive > External Documentation > Blog posts > your_filename* to draft the copy for your new page, with a title of the form "[VERSION #] <your_title>" and append this title with "(ES)" if the draft is in Spanish.

Please consult the [Style Guide](https://docs.google.com/document/d/1qMSvTmqBuBow98tvxgNvsVZB9eo-pItWfGZPy8W_cok/edit?usp=sharing) for more information, including which metadata tags to choose from for your blog post.

Google doc for drafting copy: https://docs.google.com/document/d/1k4PnUOzcxggpnFNu9g6cVpZGDexRvwM1k0G8lMbgSTw/edit

**Roles**

- [x] Drafting content: @katiepratt 
- [x] Sub-team review: @jnywong @Tajuddeen1 @LouWoodley 
- [x] Send to Author for sign off @katiepratt 
- [x] Any corrections made / final sign off @katiepratt 
- [x] Hand off to @SLLDeC for translation
- [x] Hand off to Jenny to draft website previews - 2 separate posts @jnywong 
- [x] Final approval of English post by Katie @katiepratt 
- [x] Final approval of Spanish post by @4iro

**Comment by Tajuddeen1** [comment]
Looks good to me

**Comment by LouWoodley** [comment]
Thanks for your work on this @katiepratt! It looks great and there are some lovely quotes. I made a couple of very minor edits.

**Comment by katiepratt** [comment]
And this one is signed off too! @jnywong

**Comment by SLLDeC** [comment]
Hi @jnywong, the translated document is available [here](https://docs.google.com/document/d/1Pe4Wf2oB8oIihTwYqI_CfJlFC9CiqEBkPuJET-MwHcY/edit?usp=drive_link).
I made a small addition in both languages regarding that MetaDocencia delivers the Carpentries Instructor Training.

**Comment by jnywong** [comment]
@katiepratt @lauracion is ready for your final approval, preview at #105 (check the box at the top of this issue when you are done). The publish date is set to Oct 28.

**Comment by katiepratt** [comment]
Thanks, @jnywong - these all look great!

**Comment by lauracion** [comment]
@jnywong, Irene Vazano, [@4iro](https://github.com/4iro),  will check this on MetaDocencia´s behalf. Can you please add her to this project so she can be added and tagged on these issues? Thank you!

**Comment by 4iro** [comment]
@jnywong and @katiepratt, the Spanish version is OK. I just want to mention that the links in the post lead to content in English. I'm not sure if they are available in Spanish.
